//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageProcessing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageProcessing.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popraw kontrast.
        /// </summary>
        internal static string AdjustContrast {
            get {
                return ResourceManager.GetString("AdjustContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja.
        /// </summary>
        internal static string BasicEdition {
            get {
                return ResourceManager.GetString("BasicEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konwertuj na czarno-biały.
        /// </summary>
        internal static string BlackAndWhite {
            get {
                return ResourceManager.GetString("BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolory.
        /// </summary>
        internal static string ColorEdition {
            get {
                return ResourceManager.GetString("ColorEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontrast+1.
        /// </summary>
        internal static string Contrast1 {
            get {
                return ResourceManager.GetString("Contrast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontrast +10.
        /// </summary>
        internal static string Contrast10 {
            get {
                return ResourceManager.GetString("Contrast10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontrast +5.
        /// </summary>
        internal static string Contrast5 {
            get {
                return ResourceManager.GetString("Contrast5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrast.
        /// </summary>
        internal static string ContrastEdition {
            get {
                return ResourceManager.GetString("ContrastEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konwertuj na odcienie szarości.
        /// </summary>
        internal static string Grayscale {
            get {
                return ResourceManager.GetString("Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń niebieski.
        /// </summary>
        internal static string RemoveBlue {
            get {
                return ResourceManager.GetString("RemoveBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zielony.
        /// </summary>
        internal static string RemoveGreen {
            get {
                return ResourceManager.GetString("RemoveGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń czerwony.
        /// </summary>
        internal static string RemoveRed {
            get {
                return ResourceManager.GetString("RemoveRed", resourceCulture);
            }
        }
    }
}
